kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-kubernetes-operator
  namespace: tripmonkey-staging
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-operator
    namespace: tripmonkey-staging
roleRef:
  kind: ClusterRole
  name: mongodb-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io